name: 游 Bug rapport
description: Rapport칠r en fejl eller uventet adf칝rd fra systemet.
labels: ['bug']

body:
- type: markdown
  attributes:
    value: |
      - [x] Fejl

      Tak fordi du rapporterer en fejl! Brug nedenst친ende sektioner til kun at indsende en fejl, hvis den er relateret vores hjemmeside / systemer.

      - Alle fejlrapporter er velkomne - vi vil gerne rette dem!
      - Systemet og hjemmesiden vedligeholdes af frivillige. V칝r venlig og t친lmodig. 游뗵
      - Husk at inkludere tilstr칝kkelige detaljer og kontekst.
      - Hvis du har flere sp칮rgsm친l, forslag eller fejl, skal du indsende dem som separate problemer.
      - Vi accepterer pull requests. Hvis du ved, hvordan du l칮ser det - g친 i gang! Hvis du ved, hvordan du laver det - g친 i gang!

      Angiv venligst f칮lgende oplysninger om det problem, du st칮dte p친. Problemer, der ikke indeholder de oplysninger, der anmodes om i denne formular, vil blive markeret som ufuldst칝ndige og automatisk lukket.

- type: input
  id: location
  validations:
    required: true
  attributes:
    label: Lokation
    description: |
        Hvilken side har du problemer med?

        Brug sidens navn eller kopier og inds칝t URL / link. Vi 칮nsker ikke at bruge al tiden p친 at diagnosticere problemer med den forkerte pr칮ve, vel?
- type: markdown
  attributes:
    value: |
      Giv en klar og pr칝cis beskrivelse af, hvad fejlen er. Du er ligeledes ogs친 velkommen til at uploade screenshots, s친 vi kan se fejlen i praksis.
- type: textarea
  id: what-happened
  attributes:
    label: Hvad skete der?
    description: Beskriv den observerede adf칝rd
    placeholder: Fort칝l os hvad du s친!
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps til at genskabe fejlen
    description: Hvordan genskaber du dette? Venligst giv s친 mange detaljer som muligt trin for trin.
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Forventet adf칝rd
    description: Hvad forventede du der ville ske?
    placeholder: Fort칝l os hvad du havde regnet med hvad der ville ske!
  validations:
    required: true
