name: 💡 Forslag
description: Foreslå en forbedring for at gøre en af vores eksempler endnu bedre
labels: ['Behov: Triage :mag:', 'type:forbedring']

body:
- type: markdown
  attributes:
    value: |

      Tak for dit forslag! Brug nedenstående sektioner til at indsende et forslag **kun** hvis det er relateret til eksempler i dette repo.

      - Forslag, der ikke følger nedenstående skabelon, vil automatisk blive lukket
      - Alle idéer er velkomne - lad os bygge noget sammen!
      - Dette system / hjemmeside vedligeholdes af frivillige. Vær venlig og tålmodig. 🙂
      - Husk at inkludere tilstrækkelige detaljer og kontekst.
      - Hvis du har flere forslag, bedes du indsende dem separat, så vi kan spore løsningen.
      - Skærmbilleder er altid nyttige (indsæt blot billeder direkte her i forslaget)

- type: input
  id: location
  validations:
    required: true
  attributes:
    label: Lokation
    description: |
        Hvor skal dit forslag være implementeret?

        Brug sidens navn eller URL.
- type: textarea
  id: suggestion
  attributes:
    label: Forslag
    description: Hvad vil du gerne se forbedret, eller har du en ny funktionalitet du kunne tænke dig at se?
    placeholder: Jo flere detaljer, jo bedre
  validations:
    required: true
