default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:development, :db, :database) %>
  username: <%= Rails.application.credentials.dig(:development, :db, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :db, :password) %>

test:
  <<: *default
  database: sif_holbaek_test
  timeout: 5000
  host: localhost
  username: deploy
  password: P8jrGza#o3IldO

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production, :db, :database) %>
  username: <%= Rails.application.credentials.dig(:production, :db, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :db, :password) %>
